#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=0

start() {
	local enabled iface

	enabled="$(uci -q get pppoe-assist.main.enabled)"
	[ "$enabled" = "1" ] || return 0

	mkdir -p /var/run/pppoe-assist

	iface="$(uci -q get pppoe-assist.main.interface)"
	[ -n "$iface" ] || iface="wan"

	/usr/bin/pppoe-assist-check "$iface" manual &
}

stop() {
	rm -rf /var/run/pppoe-assist
}

reload() {
	local enabled

	enabled="$(uci -q get pppoe-assist.main.enabled)"
	if [ "$enabled" = "1" ]; then
		start
	else
		stop
	fi
}

restart() {
	stop
	start
}
